# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &AXIS
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: AXISMSP

        # ID to load the MSP definition as
        ID: AXISMSP

        MSPDir: ../organizations/peerOrganizations/axis.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AXISMSP.admin', 'AXISMSP.peer', 'AXISMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AXISMSP.admin', 'AXISMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AXISMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('AXISMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.axis.example.com
              Port: 11051
